### ISSUE TITLE
Login page not displaying

### ISSUE THREAD

**Issue by tealeafnguyen** [TeamNotSoBad/demo-web-project#2]
I created a login page using html, but I can't seem to display it when I use a get request and use ModelAndView. I will probably use the freemarker thing instead and try to get the page to display; unless anyone wants to take a crack at it.

**Comment by mailog** [comment]
I've created a home page, sign up, search and edit profile page using freemarker. Its pretty bare minimum at the moment, but I'm working on making it look nicer so no one really needs to worry about that part. As far as the database, can't we just do it using using a hash map for now? That's what he uses in the demo web project.

**Comment by mailog** [comment]
Heres the homepage atm. 
![screenshot 2](https://cloud.githubusercontent.com/assets/15113438/16572288/ec32dfd4-421b-11e6-99bb-e105d768cd06.png)

**Comment by tealeafnguyen** [comment]
We can just use the hash map, what I was trying to do was to be able to upload that hash map so that we can access that hash map from any pc.

**Comment by mailog** [comment]
Oh yeah thats true lol. Uh I'm positive there's a way to upload to it somewhere, probably as a file saved on the server though.

**Comment by tealeafnguyen** [comment]
I'm working on that right now, trying to get the aws to accept my credentials to use my bucket which lets me store around 5gb. That's listed on the other issue for downloading and uploading.

**Comment by mailog** [comment]
So its not letting others access the file unless they have a key? Is there a way to tie the key to their account on creation somehow?

**Comment by tealeafnguyen** [comment]
It's just not letting me accept my credentials at all; at this rate I might have to look for another service to upload the map.

What I'm thinking about doing is to make a public key that's tied to the program itself, in turn allows the users to modify the map. Since we don't have any security, might as well just do things to get this project to work.

**Comment by mailog** [comment]
Yeah thats what i was going to suggest. I dont think we need to worry about security at the moment.

**Comment by Liukevin5** [comment]
Can't we create methods that allow users to access the hashmap, though? And maybe associate these methods with buttons.

**Comment by tealeafnguyen** [comment]
We can, but we need a way to upload and download the hash map because the current one is stored locally.

**Comment by Liukevin5** [comment]
locally as in each client has their own hashmap?

**Comment by tealeafnguyen** [comment]
I think we have our own seperate hash maps locally, which is  why I wanted a main hash map that is accessed anywhere.

**Comment by Liukevin5** [comment]
Oh, I thought that it'd be the server that kept the hashmap, but if that's the case then I can see the problem.

**Comment by tealeafnguyen** [comment]
Getting a database running would take some time, for now we should get the other things up and running.
